# Generated by Django 4.0.4 on 2022-04-27 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airpollution', '0003_remove_country_id_country_iso_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollutantentry',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='entries_country', to='airpollution.country'),
            preserve_default=False,
        ),
    ]
