# Generated by Django 4.0.4 on 2022-04-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airpollution', '0004_pollutantentry_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollutantentry',
            name='pollution_level',
            field=models.FloatField(),
        ),
    ]
