# Generated by Django 4.0.4 on 2022-04-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airpollution', '0005_alter_pollutantentry_pollution_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollutantentry',
            name='pollution_level',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
