# Generated by Django 4.0.4 on 2022-05-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airpollution', '0008_pollutant_limit_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='color',
            field=models.CharField(default='#000000', max_length=10),
        ),
    ]
