# Generated by Django 4.0.4 on 2022-05-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airpollution', '0009_country_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollutant',
            name='color',
            field=models.CharField(default='#000000', max_length=10),
        ),
    ]
