# Generated by Django 4.0.4 on 2022-04-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_myapp_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myapp',
            name='url',
            field=models.CharField(max_length=40),
        ),
    ]
